### ISSUE TITLE
НЕакуратний код

### ISSUE THREAD

**Issue by nabat** [Kalifornia2019/Trees_project#6]

**Comment by nabat** [comment]
my $list = $Trees->search(
      {
        TREE_AGE    => $FORM{AGE},
        TREE_HEIGHT => $FORM{HEIGHT},
        TREE_CIRCLE => $FORM{CIRCLE},
        TREE_TYPE   => $FORM{ADD_TREE_SORT},
        TREE_STATUS => $FORM{STATUS},
        VALUE_X     => $FORM{VALUE_X},
        VALUE_Y     => $FORM{VALUE_Y},
        COMMENT     => $FORM{COMMENT},
        ,
        COLS_NAME => 1
      }
    );



дуже багато лишніх рядків

**Comment by vintoniak** [comment]
fixed
